# Generated by Django 4.1.7 on 2023-03-31 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_choice'),
    ]

    operations = [
        migrations.RenameField(
            model_name='choice',
            old_name='choice_text',
            new_name='text',
        ),
        migrations.AddField(
            model_name='choice',
            name='is_true',
            field=models.BooleanField(default=False),
        ),
    ]
